[package]
name = "nix_integration_tests"
version.workspace = true
readme.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
base.workspace = true

uuid.workspace = true
tokio.workspace = true