name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    # container:
    # image: node:20
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        # with:
        # init: none
        # planner: linux
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#test || nix log /nix/store/q52d3ayxq3c6cik33qgm51mb73mhmqxw-heavy_computer-deps-0.0.0.drv
      # - run: nix build .#wheel
      # - run: nix build .#docker
      # - run: nix build .#coverage_lcov
