name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          init: none
          planner: linux
          extra-conf: "system-features = nixos-test benchmark big-parallel kvm"
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check -L
      - run: nix build .#wheel
      - run: nix build .#docker
      - run: nix build .#coverage_lcov
