name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    # Need to run on a docker container, the raw machine is weird and
    # makes nix fail. Need node for the checkout action.
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          init: none
          planner: linux
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#test
      - run: nix build .#wheel
      - run: nix build .#docker
      - run: nix build .#coverage_lcov
